apiVersion: apps/v1
kind: Deployment
metadata:
  name: argohelm-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: argohelm-app
  template:
    metadata:
      labels:
        app: argohelm-app
    spec:
      containers:
      - name: argohelm-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080